import { ArrowRight, CheckCircle2, Clock3, CreditCard, HeartPulse, MapPin, MessageCircle, PackageCheck, Play, ShieldCheck, Sparkles, Stethoscope, Truck, Video } from 'lucide-react';
import Link from 'next/link';
import { BrandMark } from '@/components/shared/BrandMark';
import { LanguageToggle } from '@/components/shared/LanguageToggle';
import { TrustBadges } from '@/components/shared/TrustBadges';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { formatKES } from '@/lib/utils/format-currency';

const services = [
  { title: 'Talk to a clinician', description: 'Video, voice, or chat with licensed Kenyan providers from wherever you are.', icon: Video, color: 'bg-blue-50 text-blue-700', action: 'Book a consultation' },
  { title: 'Get your medicines', description: 'Browse a trusted pharmacy catalog and upload a prescription in minutes.', icon: PackageCheck, color: 'bg-[var(--color-primary-light)] text-[var(--color-primary-dark)]', action: 'Explore pharmacy' },
  { title: 'Track every delivery', description: 'From pharmacy shelf to your landmark, see your rider and chain of custody.', icon: Truck, color: 'bg-orange-50 text-orange-700', action: 'See how it works' }
];

const steps = [
  { number: '01', title: 'Tell us what you need', description: 'Browse care options, order medicines, or share a prescription securely.' },
  { number: '02', title: 'Pay with M-PESA', description: 'Fast, familiar payment with clear updates at every step.' },
  { number: '03', title: 'Receive with care', description: 'Discreet delivery to your phone and landmark, with live tracking.' }
];

export default function HomePage() {
  return (
    <div className="overflow-hidden bg-white">
      <header className="border-b border-[var(--color-gray-100)]">
        <div className="container-shell flex h-20 items-center justify-between gap-4">
          <BrandMark />
          <nav className="hidden items-center gap-7 text-sm font-semibold text-[var(--color-gray-600)] lg:flex" aria-label="Main navigation">
            <a href="#care" className="hover:text-[var(--color-primary-dark)]">How it works</a>
            <a href="#pharmacy" className="hover:text-[var(--color-primary-dark)]">Pharmacy</a>
            <a href="#trust" className="hover:text-[var(--color-primary-dark)]">Trust & safety</a>
            <a href="#stories" className="hover:text-[var(--color-primary-dark)]">Patient stories</a>
          </nav>
          <div className="flex items-center gap-2"><LanguageToggle /><Link href="/login" className="hidden min-h-11 items-center rounded-lg px-3 text-sm font-bold text-[var(--color-gray-700)] hover:bg-[var(--color-gray-100)] sm:inline-flex">Sign in</Link><Link href="/register" className="inline-flex min-h-11 items-center rounded-lg bg-[var(--color-primary)] px-4 text-sm font-bold text-white hover:bg-[var(--color-primary-dark)]">Get started</Link></div>
        </div>
      </header>

      <main>
        <section className="relative bg-[#f5fcf7]">
          <div className="absolute -right-40 top-20 h-[34rem] w-[34rem] rounded-full bg-[#d8f5e1] blur-3xl" />
          <div className="container-shell relative grid items-center gap-12 py-16 lg:grid-cols-[1.05fr_0.95fr] lg:py-24">
            <div>
              <Badge tone="primary" className="mb-5"><Sparkles className="h-3.5 w-3.5" />Kenya’s health, one tap away</Badge>
              <h1 className="max-w-2xl text-balance text-4xl font-extrabold leading-[1.08] tracking-tight text-[var(--color-gray-900)] sm:text-5xl lg:text-6xl">Your health, <span className="text-[var(--color-primary)]">delivered.</span></h1>
              <p className="mt-6 max-w-xl text-lg leading-8 text-[var(--color-gray-600)]">From a trusted consultation to your doorstep, AfyaCommerce brings quality healthcare and pharmacy essentials closer to every Kenyan family.</p>
              <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[var(--color-primary)] px-6 text-base font-bold text-white transition hover:bg-[var(--color-primary-dark)]">Start your care journey<ArrowRight className="h-4 w-4" /></Link><Link href="/pharmacy" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border border-[var(--color-primary)] bg-white px-6 text-base font-bold text-[var(--color-primary-dark)] transition hover:bg-[var(--color-primary-light)]"><PackageCheck className="h-4 w-4" />Browse pharmacy</Link></div>
              <div className="mt-8 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs font-semibold text-[var(--color-gray-600)]"><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4 text-[var(--color-primary)]" />Licensed providers</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4 text-[var(--color-primary)]" />M-PESA ready</span><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4 text-[var(--color-primary)]" />PPB verified</span></div>
            </div>
            <div className="relative mx-auto w-full max-w-lg">
              <div className="absolute -inset-4 rounded-[2rem] bg-gradient-to-br from-[#d9f7e2] to-[#e9f3ff] opacity-70 blur-2xl" />
              <Card className="relative overflow-hidden border-white/80 p-0 shadow-xl">
                <div className="flex items-center justify-between border-b border-[var(--color-gray-100)] px-5 py-4"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[var(--color-primary-light)] text-[var(--color-primary-dark)]"><HeartPulse className="h-4 w-4" /></span><span className="text-sm font-extrabold">Your care plan</span></div><span className="text-xs font-semibold text-[var(--color-primary-dark)]">Active</span></div>
                <div className="space-y-4 p-5">
                  <div className="rounded-xl bg-[#f5fcf7] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-[var(--color-primary-dark)]">Next appointment</p><p className="mt-1 font-bold">Dr. Amina Hassan</p><p className="mt-1 text-sm text-[var(--color-gray-500)]">General practice · Today, 14:30</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#b9ebca] text-xs font-extrabold text-[var(--color-primary-dark)]">AH</span></div><div className="mt-4 flex items-center gap-2 text-xs font-semibold text-[var(--color-gray-600)]"><Video className="h-4 w-4 text-[var(--color-secondary)]" />Video consultation <span className="mx-1 text-[var(--color-gray-300)]">•</span> 20 min</div></div>
                  <div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-[var(--color-gray-200)] p-3"><MapPin className="h-4 w-4 text-[var(--color-accent)]" /><p className="mt-2 text-xs text-[var(--color-gray-500)]">Delivery to</p><p className="mt-0.5 text-sm font-bold">Kasarani, Nairobi</p></div><div className="rounded-xl border border-[var(--color-gray-200)] p-3"><PackageCheck className="h-4 w-4 text-[var(--color-primary)]" /><p className="mt-2 text-xs text-[var(--color-gray-500)]">Order status</p><p className="mt-0.5 text-sm font-bold">On the way</p></div></div>
                  <div className="flex items-center justify-between rounded-xl border border-[var(--color-gray-200)] p-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-blue-700"><Stethoscope className="h-4 w-4" /></span><div><p className="text-sm font-bold">Prescription ready</p><p className="text-xs text-[var(--color-gray-500)]">Collect at a pickup point</p></div></div><ArrowRight className="h-4 w-4 text-[var(--color-gray-400)]" /></div>
                </div>
              </Card>
              <div className="absolute -bottom-5 -left-6 hidden items-center gap-2 rounded-xl border border-[var(--color-gray-100)] bg-white px-4 py-3 text-xs font-bold shadow-lg sm:flex"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[var(--color-primary-light)] text-[var(--color-primary-dark)]"><ShieldCheck className="h-4 w-4" /></span>Trusted by 12,000+ patients</div>
            </div>
          </div>
        </section>

        <section id="care" className="container-shell py-16 lg:py-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">One connected platform</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Care that meets you where you are</h2><p className="mt-4 text-base leading-7 text-[var(--color-gray-600)]">Whether you need a clinician, a refill, or a delivery update, we keep the experience simple, private, and reliable.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{services.map((service) => { const Icon = service.icon; return <Card key={service.title} className="group transition hover:-translate-y-1 hover:shadow-lg"><span className={`flex h-12 w-12 items-center justify-center rounded-xl ${service.color}`}><Icon className="h-6 w-6" aria-hidden="true" /></span><h3 className="mt-5 text-xl font-extrabold">{service.title}</h3><p className="mt-2 min-h-14 text-sm leading-6 text-[var(--color-gray-600)]">{service.description}</p><Link href={service.title.includes('pharmacy') ? '/pharmacy' : service.title.includes('delivery') ? '/orders' : '/consultations/book'} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--color-primary-dark)]">{service.action}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link></Card>; })}</div></section>

        <section id="pharmacy" className="bg-[#092b1a] py-16 text-white lg:py-24"><div className="container-shell grid items-center gap-12 lg:grid-cols-[0.9fr_1.1fr]"><div><Badge className="border-white/20 bg-white/10 text-[#b9ebca]">Pharmacy, reimagined</Badge><h2 className="mt-5 text-3xl font-extrabold tracking-tight sm:text-4xl">The medicines you need, with the proof you need.</h2><p className="mt-5 max-w-lg text-base leading-7 text-green-100/75">Every product is sourced from a licensed Kenyan pharmacy, with PPB registration, stock visibility, and discreet delivery built in.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="flex items-center gap-3 text-sm font-semibold text-green-50"><CheckCircle2 className="h-5 w-5 text-[#8de5aa]" />Prescription-safe catalog</div><div className="flex items-center gap-3 text-sm font-semibold text-green-50"><CheckCircle2 className="h-5 w-5 text-[#8de5aa]" />Transparent pricing</div><div className="flex items-center gap-3 text-sm font-semibold text-green-50"><CheckCircle2 className="h-5 w-5 text-[#8de5aa]" />Bilingual search</div><div className="flex items-center gap-3 text-sm font-semibold text-green-50"><CheckCircle2 className="h-5 w-5 text-[#8de5aa]" />Live delivery updates</div></div><Link href="/pharmacy" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-lg bg-white px-6 font-bold text-[#092b1a] hover:bg-[#e8f7ed]">Explore the catalog<ArrowRight className="h-4 w-4" /></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/10 p-5 backdrop-blur"><p className="text-sm font-semibold text-green-100/70">Trusted fulfillment</p><p className="mt-6 text-4xl font-extrabold">4.9<span className="text-xl text-[#8de5aa]">/5</span></p><p className="mt-2 text-sm text-green-100/70">Patient delivery rating</p><div className="mt-6 flex gap-1 text-[#8de5aa]">★★★★★</div></div><div className="rounded-2xl border border-white/10 bg-white/10 p-5 backdrop-blur"><p className="text-sm font-semibold text-green-100/70">Average delivery</p><p className="mt-6 text-4xl font-extrabold">2.4<span className="text-xl text-[#8de5aa]"> hrs</span></p><p className="mt-2 text-sm text-green-100/70">Within Nairobi service area</p><div className="mt-6 flex items-center gap-2 text-sm font-semibold text-[#8de5aa]"><Clock3 className="h-4 w-4" />Same-day options</div></div><div className="rounded-2xl border border-[#1da84a]/40 bg-[#1da84a]/20 p-5 sm:col-span-2"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#8de5aa] text-[#092b1a]"><ShieldCheck className="h-5 w-5" /></span><div><p className="font-extrabold">Your privacy travels with you</p><p className="mt-1 text-sm leading-6 text-green-100/75">Minimal packaging, landmark-based delivery, and consent controls are always available in your profile.</p></div></div></div></div></div></section>

        <section className="container-shell py-16 lg:py-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Simple by design</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">From concern to care in three steps</h2></div><div className="mt-12 grid gap-8 md:grid-cols-3">{steps.map((step) => <div key={step.number} className="relative"><div className="flex items-center gap-4"><span className="font-mono text-sm font-bold text-[var(--color-primary)]">{step.number}</span><span className="h-px flex-1 bg-[var(--color-gray-200)]" /></div><h3 className="mt-5 text-xl font-extrabold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--color-gray-600)]">{step.description}</p></div>)}</div></section>

        <section id="trust" className="border-y border-[var(--color-gray-200)] bg-[var(--color-gray-50)] py-14"><div className="container-shell flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="eyebrow">Trust is part of the care</p><h2 className="mt-2 text-2xl font-extrabold">Regulated, secure, and accountable</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--color-gray-600)]">We show the details that matter: who is prescribing, which pharmacy is dispensing, and what happens next.</p></div><div className="rounded-xl border border-[var(--color-gray-200)] bg-white p-4"><TrustBadges ppbLicence="PPB/2026/AFY-1048" kmhfrId="KMHFR-KE-8821" pharmacistRegNo="PPB-P-77842" isShaEmpanelled /></div></div></section>

        <section id="stories" className="container-shell py-16 lg:py-24"><div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">A better care experience</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Healthcare that respects your time.</h2><p className="mt-4 text-base leading-7 text-[var(--color-gray-600)]">“I could see exactly when my medicines would arrive and speak to my pharmacist without leaving home. It made managing my mother’s care so much easier.”</p><div className="mt-6 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#d8f5e1] font-bold text-[var(--color-primary-dark)]">MN</span><div><p className="text-sm font-bold">Miriam Njeri</p><p className="text-xs text-[var(--color-gray-500)]">Patient since 2025 · Nairobi</p></div></div><Button variant="outline" className="mt-7"><Play className="h-4 w-4" />Hear her story</Button></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[#f5fcf7] p-5 sm:translate-y-8"><MessageCircle className="h-6 w-6 text-[var(--color-primary)]" /><p className="mt-8 text-sm font-bold">“A real clinician listened to the whole story.”</p><p className="mt-3 text-xs text-[var(--color-gray-500)]">— Peter, Kisumu</p></div><div className="rounded-2xl bg-[#eef6ff] p-5"><Truck className="h-6 w-6 text-[var(--color-secondary)]" /><p className="mt-8 text-sm font-bold">“The delivery update meant no more waiting by the door.”</p><p className="mt-3 text-xs text-[var(--color-gray-500)]">— Amina, Mombasa</p></div><div className="rounded-2xl bg-[#fff4ed] p-5 sm:translate-y-8"><CreditCard className="h-6 w-6 text-[var(--color-accent)]" /><p className="mt-8 text-sm font-bold">“M-PESA made checkout feel completely familiar.”</p><p className="mt-3 text-xs text-[var(--color-gray-500)]">— Joseph, Nakuru</p></div></div></div></section>
      </main>

      <footer className="bg-[#092b1a] py-12 text-green-100/75"><div className="container-shell grid gap-10 lg:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><BrandMark /><p className="mt-5 max-w-xs text-sm leading-6">Quality healthcare, trusted pharmacy services, and a clearer way to care for your family.</p><div className="mt-5"><TrustBadges ppbLicence="PPB/2026/AFY-1048" kmhfrId="KMHFR-KE-8821" pharmacistRegNo="PPB-P-77842" isShaEmpanelled /></div></div><div><p className="font-bold text-white">Explore</p><div className="mt-4 space-y-3 text-sm"><Link href="/consultations/book" className="block hover:text-white">Book a consultation</Link><Link href="/pharmacy" className="block hover:text-white">Pharmacy catalog</Link><Link href="/orders" className="block hover:text-white">Track an order</Link></div></div><div><p className="font-bold text-white">Support</p><div className="mt-4 space-y-3 text-sm"><Link href="/help" className="block hover:text-white">Help centre</Link><Link href="/profile/consent" className="block hover:text-white">Privacy & consent</Link><Link href="/profile/data-rights" className="block hover:text-white">Your data rights</Link></div></div><div><p className="font-bold text-white">Stay connected</p><p className="mt-4 text-sm leading-6">Get medicine reminders and care tips over SMS.</p><div className="mt-4 flex gap-2"><span className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold text-white">M-PESA</span><span className="rounded-lg bg-white/10 px-3 py-2 text-xs font-bold text-white">SHA</span></div></div></div><div className="container-shell mt-10 border-t border-white/10 pt-6 text-xs">© 2026 AfyaCommerce. Built for healthier communities.</div></footer>
    </div>
  );
}
