name = "afyacommerce-dispatch"
main = "src/index.ts"
compatibility_date = "2026-09-25"

[vars]
ALLOWED_ORIGIN = "https://afyacommerce.co.ke"

[[kv_namespaces]]
binding = "DISPATCH_EVENTS"
id = "90f0bff82d244a6cba6f8822dfc74f1b"

[[queues.producers]]
binding = "SMS_QUEUE"
queue = "afyacommerce-sms-jobs"

[[queues.consumers]]
queue = "afyacommerce-dispatch-jobs"
