'use client';

import { Check, Info, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useState } from 'react';
import { ConsentGate } from '@/components/shared/ConsentGate';
import { PageHeader } from '@/components/shared/PageHeader';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

export default function ConsentPage() {
  const [saved, setSaved] = useState(false);
  const [sharing, setSharing] = useState(true);
  return <div><PageHeader eyebrow="Privacy centre" title="Consent & permissions" description="Choose exactly how AfyaCommerce may use your information. Changes are timestamped and recorded." /><div className="grid gap-6 lg:grid-cols-[1fr_0.7fr]"><div className="space-y-6"><ConsentGate defaultGranted onConsent={() => setSaved(false)} /><Card><div className="flex items-center justify-between gap-3"><div><h2 className="font-extrabold">Prescription sharing</h2><p className="mt-1 text-xs text-[var(--color-gray-500)]">Allow verified pharmacies to view prescriptions routed to them.</p></div><button type="button" onClick={() => { setSharing((value) => !value); setSaved(false); }} className={`relative h-7 w-12 rounded-full transition ${sharing ? 'bg-[var(--color-primary)]' : 'bg-[var(--color-gray-300)]'}`} aria-pressed={sharing} aria-label="Prescription sharing"><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${sharing ? 'left-6' : 'left-1'}`} /></button></div><div className="mt-4 flex items-center gap-2 text-xs text-[var(--color-gray-500)]"><SlidersHorizontal className="h-4 w-4" />Last updated 18 Sep 2026 at 14:20</div></Card><Card><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-[var(--color-primary)]" /><h2 className="font-extrabold">Research & analytics</h2></div><p className="mt-2 text-sm leading-6 text-[var(--color-gray-600)]">We never use identifiable health information for research without separate, specific consent.</p><label className="mt-4 flex items-center justify-between gap-3 rounded-lg bg-[var(--color-gray-50)] p-3"><span className="text-sm font-semibold">Allow anonymised service insights</span><input type="checkbox" className="h-5 w-5 accent-[var(--color-primary)]" defaultChecked={false} /></label></Card><Button onClick={() => setSaved(true)}>{saved ? <><Check className="mr-2 h-4 w-4" />Consent saved</> : 'Save consent choices'}</Button></div><Card className="h-fit"><div className="flex items-center gap-2"><Info className="h-5 w-5 text-[var(--color-secondary)]" /><h2 className="font-extrabold">Your rights</h2></div><p className="mt-3 text-sm leading-6 text-[var(--color-gray-600)]">Under the Kenya Data Protection Act, you can ask what information we hold, request a copy, correct inaccurate details, or withdraw consent.</p><div className="mt-5 space-y-3 text-sm"><a href="/profile/data-rights" className="flex items-center justify-between rounded-lg bg-[var(--color-gray-50)] p-3 font-semibold hover:bg-[var(--color-gray-100)]">Access my data <span>→</span></a><a href="/profile/data-rights#delete" className="flex items-center justify-between rounded-lg bg-[var(--color-gray-50)] p-3 font-semibold hover:bg-[var(--color-gray-100)]">Request deletion <span>→</span></a></div><Badge tone="info" className="mt-5">Policy version 1.0.0</Badge></Card></div></div>;
}
