name = "afyacommerce-fhir"
main = "src/index.ts"
compatibility_date = "2026-09-25"

[vars]
ALLOWED_ORIGIN = "https://afyacommerce.co.ke"

[[kv_namespaces]]
binding = "HIE_TOKEN_CACHE"
id = "81e1a5f85d504d3780175c3b28d15aff"

[[kv_namespaces]]
binding = "HIE_REQUEST_CACHE"
id = "a43cbb09c7b5417fa5ee327c8246497e"
