import { Bell, ChevronRight, FileText, KeyRound, Languages, LockKeyhole, LogOut, ShieldCheck, UserRound } from 'lucide-react';
import Link from 'next/link';
import type { Route } from 'next';
import { PageHeader } from '@/components/shared/PageHeader';
import { LanguageToggle } from '@/components/shared/LanguageToggle';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';

export default function ProfilePage() {
  return <div><PageHeader eyebrow="Your account" title="Profile & settings" description="Manage your identity, preferences, and privacy controls." /><div className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr]"><Card><div className="flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-[#b9ebca] text-xl font-extrabold text-[var(--color-primary-dark)]">JW</span><div><h2 className="text-lg font-extrabold">James Wanjiku</h2><p className="mt-1 text-sm text-[var(--color-gray-500)]">Patient · Nairobi</p><Badge tone="success" className="mt-2">Account active</Badge></div></div><div className="mt-5 space-y-2 border-t border-[var(--color-gray-100)] pt-5 text-sm"><p className="flex items-center gap-2 text-[var(--color-gray-600)]"><UserRound className="h-4 w-4 text-[var(--color-gray-500)]" />+254 712 345 678</p><p className="flex items-center gap-2 text-[var(--color-gray-600)]"><LockKeyhole className="h-4 w-4 text-[var(--color-gray-500)]" />MFA not configured</p></div><button type="button" className="mt-5 inline-flex min-h-11 items-center gap-2 text-xs font-bold text-red-700"><LogOut className="h-4 w-4" />Sign out</button></Card><div className="space-y-4"><Card className="p-0"><SettingsRow icon={Languages} title="Language" description="Choose the language for your AfyaCommerce experience" action={<LanguageToggle />} /><SettingsRow icon={Bell} title="Notifications" description="SMS reminders for orders, refills, and appointments" action={<button type="button" className="text-xs font-bold text-[var(--color-primary-dark)]">Manage</button>} /><SettingsRow icon={ShieldCheck} title="Privacy & consent" description="Control how your health information is used" href="/profile/consent" /><SettingsRow icon={FileText} title="Your data rights" description="Download or request deletion of your personal data" href="/profile/data-rights" /><SettingsRow icon={KeyRound} title="Security" description="Set up multi-factor authentication" action={<button type="button" className="text-xs font-bold text-[var(--color-primary-dark)]">Set up</button>} /></Card><Card className="border-green-100 bg-green-50"><div className="flex items-start gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-green-700" /><p className="text-sm leading-6 text-green-800"><strong>Your privacy is active.</strong> AfyaCommerce records every access to your health information for your protection and regulatory accountability.</p></div></Card></div></div></div>;
}

function SettingsRow({ icon: Icon, title, description, action, href }: { icon: React.ElementType; title: string; description: string; action?: React.ReactNode; href?: Route }) {
  const content = <div className="flex min-h-20 items-center gap-4 px-5 py-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[var(--color-gray-100)] text-[var(--color-gray-600)]"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">{title}</span><span className="mt-1 block text-xs text-[var(--color-gray-500)]">{description}</span></span>{action ?? (href ? <ChevronRight className="h-4 w-4 text-[var(--color-gray-400)]" /> : null)}</div>;
  return href ? <Link href={href} className="block border-b border-[var(--color-gray-100)] last:border-0 hover:bg-[var(--color-gray-50)]">{content}</Link> : <div className="border-b border-[var(--color-gray-100)] last:border-0">{content}</div>;
}
