import Link from 'next/link';
import { ArrowRight, CreditCard, MapPin, ShoppingBag } from 'lucide-react';
import { OrderSummary } from '@/components/checkout/OrderSummary';
import { PageHeader } from '@/components/shared/PageHeader';
import { Card } from '@/components/ui/card';

export default function CheckoutPage() {
  return <div><PageHeader eyebrow="Secure checkout" title="Let’s get your order to you" description="Choose delivery first, then complete payment with your preferred method." /><div className="grid gap-6 lg:grid-cols-[1fr_0.38fr]"><div className="space-y-4"><Link href="/checkout/delivery" className="surface group flex items-center gap-4 p-5 transition hover:border-[var(--color-primary)]"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><MapPin className="h-6 w-6" /></span><span className="flex-1"><span className="block font-extrabold">1. Delivery details</span><span className="mt-1 block text-sm text-[var(--color-gray-500)]">Phone, landmark, county, and delivery method</span></span><ArrowRight className="h-5 w-5 text-[var(--color-gray-500)] transition group-hover:translate-x-1 group-hover:text-[var(--color-primary)]" /></Link><Link href="/checkout/payment" className="surface group flex items-center gap-4 p-5 transition hover:border-[var(--color-primary)]"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--color-primary-light)] text-[var(--color-primary-dark)]"><CreditCard className="h-6 w-6" /></span><span className="flex-1"><span className="block font-extrabold">2. Payment</span><span className="mt-1 block text-sm text-[var(--color-gray-500)]">M-PESA, Airtel Money, card, or SHA</span></span><ArrowRight className="h-5 w-5 text-[var(--color-gray-500)] transition group-hover:translate-x-1 group-hover:text-[var(--color-primary)]" /></Link><Card className="flex items-start gap-3 border-blue-100 bg-blue-50"><ShoppingBag className="mt-0.5 h-5 w-5 shrink-0 text-blue-700" /><p className="text-sm leading-6 text-blue-800"><strong>Address-free delivery.</strong> We use your phone number and a nearby landmark so your medicines arrive discreetly and reliably.</p></Card></div><OrderSummary deliveryFee={200} actionHref="/checkout/delivery" actionLabel="Start checkout" /></div></div>;
}
